---
sudo: false
language: python

matrix:
  include:
    - python: 3.5
      dist: trusty
      env: TOXENV=py35
    - python: 3.6
      dist: trusty
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

deps:
  - codecov

install:
  - pip install tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
